// Reconstructed from ~/dev/cc-statusline/node_modules/@pierre/trees/dist/index.d.ts.
//
// No src/index.ts was recovered from the upstream source maps (index.js has
// no .js.map in @pierre/trees dist, so esbuild's sourcesContent never
// captured it — same class of gap as the type-only modules elsewhere in this
// package). Recovered verbatim from the shipped .d.ts's barrel re-export
// list — only the `.js` import extensions were stripped to match this
// repo's extension-less imports. This mirrors cc-statusline's actual usage,
// which only imports `FileTree` from the package root (no react/ssr/
// web-components subpath entry points).

import {
	CONTEXT_MENU_SLOT_NAME,
	CONTEXT_MENU_TRIGGER_TYPE,
	FILE_TREE_SCROLLBAR_GUTTER_MEASURED_PROPERTY,
	FILE_TREE_SCROLLBAR_GUTTER_STYLE_ATTRIBUTE,
	FILE_TREE_SCROLLBAR_MEASURE_ATTRIBUTE,
	FILE_TREE_STYLE_ATTRIBUTE,
	FILE_TREE_TAG_NAME,
	FILE_TREE_UNSAFE_CSS_ATTRIBUTE,
	FLATTENED_PREFIX,
	HEADER_SLOT_NAME,
} from "./constants";
import type {
	FileTreeBuiltInIconSet,
	FileTreeIconConfig,
	FileTreeIcons,
	RemappedIcon,
} from "./iconConfig";
import { getBuiltInSpriteSheet } from "./builtInIcons";
import type {
	ContextMenuAnchorRect,
	GitStatus,
	GitStatusEntry,
} from "./publicTypes";
import { createFileTreeIconResolver } from "./render/iconResolver";
import {
	type TreeThemeInput,
	type TreeThemeStyles,
	themeToTreeStyles,
} from "./utils/themeToTreeStyles";
import {
	FILE_TREE_DENSITY_PRESETS,
	type FileTreeDensity,
	type FileTreeDensityKeyword,
	type FileTreeDensityPreset,
} from "./model/density";
import type {
	FileTreeAddEvent,
	FileTreeBatchEvent,
	FileTreeBatchOperation,
	FileTreeCollisionStrategy,
	FileTreeCompositionOptions,
	FileTreeContextMenuButtonVisibility,
	FileTreeContextMenuItem,
	FileTreeContextMenuOpenContext,
	FileTreeContextMenuTriggerMode,
	FileTreeDirectoryHandle,
	FileTreeDragAndDropConfig,
	FileTreeDropContext,
	FileTreeDropResult,
	FileTreeDropTarget,
	FileTreeFileHandle,
	FileTreeGitStatusPatch,
	FileTreeHeaderCompositionOptions,
	FileTreeInitialExpansion,
	FileTreeItemHandle,
	FileTreeListener,
	FileTreeMoveEvent,
	FileTreeMoveOptions,
	FileTreeMutationEvent,
	FileTreeMutationEventForType,
	FileTreeMutationEventInvalidation,
	FileTreeMutationEventType,
	FileTreeMutationHandle,
	FileTreeMutationSemanticEvent,
	FileTreeOptions,
	FileTreeRemoveEvent,
	FileTreeRemoveOptions,
	FileTreeRenameEvent,
	FileTreeRenamingConfig,
	FileTreeRenamingItem,
	FileTreeRenderOptions,
	FileTreeRenderProps,
	FileTreeResetEvent,
	FileTreeResetOptions,
	FileTreeResetPreparedOptions,
	FileTreeRowDecoration,
	FileTreeRowDecorationContext,
	FileTreeRowDecorationRenderer,
	FileTreeScrollOffset,
	FileTreeScrollToPathOptions,
	FileTreeSearchBlurBehavior,
	FileTreeSearchChangeListener,
	FileTreeSearchMode,
	FileTreeSearchSessionHandle,
	FileTreeSelectionChangeListener,
	FileTreeSortComparator,
	FileTreeSortEntry,
	FileTreeVisibleRow,
} from "./model/publicTypes";
import {
	type FileTreePreparedInput,
	prepareFileTreeInput,
	preparePresortedFileTreeInput,
} from "./preparedInput";
import { FILE_TREE_DEFAULT_ITEM_HEIGHT } from "./model/virtualization";
import { FileTree } from "./render/FileTree";

export {
	CONTEXT_MENU_SLOT_NAME,
	CONTEXT_MENU_TRIGGER_TYPE,
	type ContextMenuAnchorRect,
	type FileTreeContextMenuButtonVisibility as ContextMenuButtonVisibility,
	type FileTreeContextMenuItem as ContextMenuItem,
	type FileTreeContextMenuOpenContext as ContextMenuOpenContext,
	type FileTreeContextMenuTriggerMode as ContextMenuTriggerMode,
	FILE_TREE_DEFAULT_ITEM_HEIGHT,
	FILE_TREE_DENSITY_PRESETS,
	FILE_TREE_SCROLLBAR_GUTTER_MEASURED_PROPERTY,
	FILE_TREE_SCROLLBAR_GUTTER_STYLE_ATTRIBUTE,
	FILE_TREE_SCROLLBAR_MEASURE_ATTRIBUTE,
	FILE_TREE_STYLE_ATTRIBUTE,
	FILE_TREE_TAG_NAME,
	FILE_TREE_UNSAFE_CSS_ATTRIBUTE,
	FLATTENED_PREFIX,
	FileTree,
	type FileTreeAddEvent,
	type FileTreeBatchEvent,
	type FileTreeBatchOperation,
	type FileTreeBuiltInIconSet,
	type FileTreeCollisionStrategy,
	type FileTreeCompositionOptions,
	type FileTreeDensity,
	type FileTreeDensityKeyword,
	type FileTreeDensityPreset,
	type FileTreeDirectoryHandle,
	type FileTreeDragAndDropConfig,
	type FileTreeDropContext,
	type FileTreeDropResult,
	type FileTreeDropTarget,
	type FileTreeFileHandle,
	type FileTreeGitStatusPatch,
	type FileTreeHeaderCompositionOptions,
	type FileTreeIconConfig,
	type FileTreeIcons,
	type FileTreeInitialExpansion,
	type FileTreeItemHandle,
	type FileTreeListener,
	type FileTreeMoveEvent,
	type FileTreeMoveOptions,
	type FileTreeMutationEvent,
	type FileTreeMutationEventForType,
	type FileTreeMutationEventInvalidation,
	type FileTreeMutationEventType,
	type FileTreeMutationHandle,
	type FileTreeMutationSemanticEvent,
	type FileTreeOptions,
	type FileTreePreparedInput,
	type FileTreeRemoveEvent,
	type FileTreeRemoveOptions,
	type FileTreeRenameEvent,
	type FileTreeRenamingConfig,
	type FileTreeRenamingItem,
	type FileTreeRenderOptions,
	type FileTreeRenderProps,
	type FileTreeResetEvent,
	type FileTreeResetOptions,
	type FileTreeResetPreparedOptions,
	type FileTreeRowDecoration,
	type FileTreeRowDecorationContext,
	type FileTreeRowDecorationRenderer,
	type FileTreeScrollOffset,
	type FileTreeScrollToPathOptions,
	type FileTreeSearchBlurBehavior,
	type FileTreeSearchChangeListener,
	type FileTreeSearchMode,
	type FileTreeSearchSessionHandle,
	type FileTreeSelectionChangeListener,
	type FileTreeSortComparator,
	type FileTreeSortEntry,
	type FileTreeVisibleRow,
	type GitStatus,
	type GitStatusEntry,
	HEADER_SLOT_NAME,
	type RemappedIcon,
	type TreeThemeInput,
	type TreeThemeStyles,
	createFileTreeIconResolver,
	getBuiltInSpriteSheet,
	prepareFileTreeInput,
	preparePresortedFileTreeInput,
	themeToTreeStyles,
};
