import type { AnnotationLineMap, AnnotationSide, AnnotationSpan, AppliedThemeStyleCache, BaseCodeOptions, BaseDiffOptions, BaseDiffOptionsWithDefaults, BundledLanguage, ChangeContent, ChangeTypes, CodeColumnType, CodeToHastOptions, CodeViewDiffItem, CodeViewFileItem, CodeViewItem, CodeViewItemScrollTarget, CodeViewLayout, CodeViewLineScrollTarget, CodeViewPositionScrollTarget, CodeViewRangeScrollTarget, CodeViewScrollBehavior, CodeViewScrollTarget, ConflictResolverTypes, ContextContent, CreatePatchOptionsNonabortable, CustomPreProperties, DecorationItem, DiffAcceptRejectHunkConfig, DiffAcceptRejectHunkType, DiffIndicators, DiffLineAnnotation, DiffLineEventBaseProps, DiffTokenEventBaseProps, DiffsHighlighter, DiffsThemeNames, ExpansionDirections, ExtensionFormatMap, FileContents, FileDiffMetadata, FileHeaderRenderMode, ForceDiffPlainTextOptions, ForceFilePlainTextOptions, GapSpan, HighlighterTypes, Hunk, HunkData, HunkExpansionRegion, HunkLineType, HunkSeparators, LanguageRegistration, LineAnnotation, LineDiffTypes, LineEventBaseProps, LineInfo, LineSpans, LineTypes, MergeConflictActionPayload, MergeConflictMarkerRow, MergeConflictMarkerRowType, MergeConflictRegion, MergeConflictResolution, NumericScrollLineAnchor, ObservedAnnotationNodes, ObservedGridNodes, ParsedPatch, PendingCodeViewLayoutReset, PostRenderPhase, PrePropertiesConfig, ProcessFileConflictData, RenderDiffFilesResult, RenderDiffOptions, RenderDiffResult, RenderFileMetadata, RenderFileOptions, RenderFileResult, RenderHeaderMetadataCallback, RenderHeaderPrefixCallback, RenderRange, RenderWindow, RenderedDiffASTCache, RenderedFileASTCache, SelectedLineRange, SelectionPoint, SelectionSide, SharedRenderState, ShikiTransformer, SmoothScrollSettings, StickySpecs, SupportedLanguages, ThemeRegistration, ThemeRegistrationResolved, ThemeTypes, ThemedDiffResult, ThemedFileResult, ThemedToken, ThemesType, TokenEventBase, VirtualFileMetrics, VirtualWindowSpecs } from './types';
import { InteractionManager, pluckInteractionOptions } from './managers/InteractionManager';
import type { GetHoveredLineResult, GetLineIndexUtility, InteractionManagerBaseOptions, InteractionManagerMode, InteractionManagerOptions, LogTypes, MergeConflictActionTarget, OnDiffLineClickProps, OnDiffLineEnterLeaveProps, OnLineClickProps, OnLineEnterLeaveProps, OnTokenEventProps, SelectionWriteOptions } from './managers/InteractionManager';
import { ResizeManager } from './managers/ResizeManager';
import { FileRenderer } from './renderers/FileRenderer';
import type { FileRenderResult, FileRendererOptions } from './renderers/FileRenderer';
import { File } from './components/File';
import type { FileHydrateProps, FileOptions, FileRenderProps } from './components/File';
import { ScrollSyncManager } from './managers/ScrollSyncManager';
import { DiffHunksRenderer } from './renderers/DiffHunksRenderer';
import type { DiffHunksRendererOptions, DiffHunksRendererOptionsWithDefaults, HunksRenderResult, InjectedRow, LineDecoration, RenderedLineContext, SplitInjectedRow, SplitInjectedRowPlacement, SplitLineDecorationProps, UnifiedInjectedRowPlacement, UnifiedLineDecorationProps } from './renderers/DiffHunksRenderer';
import { FileDiff } from './components/FileDiff';
import type { FileDiffHydrationProps, FileDiffOptions, FileDiffRenderProps, FileDiffType } from './components/FileDiff';
import { Virtualizer } from './components/Virtualizer';
import type { VirtualizerConfig } from './components/Virtualizer';
import { VirtualizedFile } from './components/VirtualizedFile';
import { VirtualizedFileDiff } from './components/VirtualizedFileDiff';
import { CodeView } from './components/CodeView';
import type { CodeViewCoordinator, CodeViewLineSelection, CodeViewOptions, CodeViewRenderedDiffItem, CodeViewRenderedFileItem, CodeViewRenderedItem, CodeViewScrollListener } from './components/CodeView';
import { ALTERNATE_FILE_NAMES_GIT, COMMIT_METADATA_SPLIT, CORE_CSS_ATTRIBUTE, CUSTOM_HEADER_SLOT_ID, DEFAULT_CODE_VIEW_FILE_METRICS, DEFAULT_CODE_VIEW_LAYOUT, DEFAULT_COLLAPSED_CONTEXT_THRESHOLD, DEFAULT_EXPANDED_REGION, DEFAULT_RENDER_RANGE, DEFAULT_SMOOTH_SCROLL_SETTINGS, DEFAULT_THEMES, DEFAULT_TOKENIZE_MAX_LENGTH, DEFAULT_VIRTUAL_FILE_METRICS, DIFFS_DEVELOPMENT_BUILD, DIFFS_SCROLLBAR_GUTTER_MEASURED_PROPERTY, DIFFS_SCROLLBAR_MEASURE_ATTRIBUTE, DIFFS_TAG_NAME, EMPTY_RENDER_RANGE, FILENAME_HEADER_REGEX, FILENAME_HEADER_REGEX_GIT, FILE_CONTEXT_BLOB, GIT_DIFF_FILE_BREAK_REGEX, HEADER_METADATA_SLOT_ID, HEADER_PREFIX_SLOT_ID, HUNK_HEADER, INDEX_LINE_METADATA, MERGE_CONFLICT_BASE_MARKER_REGEX, MERGE_CONFLICT_END_MARKER_REGEX, MERGE_CONFLICT_SEPARATOR_MARKER_REGEX, MERGE_CONFLICT_START_MARKER_REGEX, SPLIT_WITH_NEWLINES, THEME_CSS_ATTRIBUTE, UNIFIED_DIFF_FILE_BREAK_REGEX, UNSAFE_CSS_ATTRIBUTE } from './constants';
import type { CodeToTokenTransformStreamOptions, RecallToken, ShikiStreamTokenizerEnqueueResult, ShikiStreamTokenizerOptions } from './shiki-stream/types';
import { ShikiStreamTokenizer } from './shiki-stream/tokenizer';
import { CodeToTokenTransformStream } from './shiki-stream/stream';
import { FileStream } from './components/FileStream';
import type { FileStreamOptions } from './components/FileStream';
import { UnresolvedFile, getUnresolvedDiffHunksRendererOptions } from './components/UnresolvedFile';
import type { MergeConflictActionsTypeOption, RenderMergeConflictActions, UnresolvedFileHydrationProps, UnresolvedFileOptions, UnresolvedFileRenderProps } from './components/UnresolvedFile';
import { areLanguagesAttached } from './highlighter/languages/areLanguagesAttached';
import { attachResolvedLanguages } from './highlighter/languages/attachResolvedLanguages';
import { cleanUpResolvedLanguages } from './highlighter/languages/cleanUpResolvedLanguages';
import { AttachedLanguages, RegisteredCustomLanguages, ResolvedLanguages, ResolvingLanguages } from './highlighter/languages/constants';
import { getResolvedLanguages } from './highlighter/languages/getResolvedLanguages';
import { getResolvedOrResolveLanguage } from './highlighter/languages/getResolvedOrResolveLanguage';
import { hasResolvedLanguages } from './highlighter/languages/hasResolvedLanguages';
import { registerCustomLanguage } from './highlighter/languages/registerCustomLanguage';
import { resolveLanguage } from './highlighter/languages/resolveLanguage';
import { resolveLanguages } from './highlighter/languages/resolveLanguages';
import { disposeHighlighter, getHighlighterIfLoaded, getSharedHighlighter, isHighlighterLoaded, isHighlighterLoading, isHighlighterNull, preloadHighlighter } from './highlighter/shared_highlighter';
import { areThemesAttached } from './highlighter/themes/areThemesAttached';
import { attachResolvedThemes } from './highlighter/themes/attachResolvedThemes';
import { cleanUpResolvedThemes } from './highlighter/themes/cleanUpResolvedThemes';
import { AttachedThemes } from './highlighter/themes/constants';
import { getResolvedOrResolveTheme } from './highlighter/themes/getResolvedOrResolveTheme';
import { getResolvedThemes } from './highlighter/themes/getResolvedThemes';
import { hasResolvedThemes } from './highlighter/themes/hasResolvedThemes';
import { registerCustomCSSVariableTheme } from './highlighter/themes/registerCustomCSSVariableTheme';
import { registerCustomTheme } from './highlighter/themes/registerCustomTheme';
import type { CustomThemeLoader } from './highlighter/themes/registerCustomTheme';
import { resolveTheme } from './highlighter/themes/resolveTheme';
import { resolveThemes } from './highlighter/themes/resolveThemes';
import { dequeueRender, queueRender } from './managers/UniversalRenderingManager';
import { SVGSpriteSheet } from './sprite';
import type { SVGSpriteNames } from './sprite';
import { areDiffLineAnnotationsEqual } from './utils/areDiffLineAnnotationsEqual';
import { areDiffRenderOptionsEqual } from './utils/areDiffRenderOptionsEqual';
import { areDiffTargetsEqual } from './utils/areDiffTargetsEqual';
import { areFileRenderOptionsEqual } from './utils/areFileRenderOptionsEqual';
import { areFilesEqual } from './utils/areFilesEqual';
import { areHunkDataEqual } from './utils/areHunkDataEqual';
import { areLineAnnotationsEqual } from './utils/areLineAnnotationsEqual';
import { areObjectsEqual } from './utils/areObjectsEqual';
import { areOptionsEqual } from './utils/areOptionsEqual';
import { arePrePropertiesEqual } from './utils/arePrePropertiesEqual';
import { areRenderRangesEqual } from './utils/areRenderRangesEqual';
import { areSelectionsEqual } from './utils/areSelectionsEqual';
import { areThemesEqual } from './utils/areThemesEqual';
import { areVirtualWindowSpecsEqual } from './utils/areVirtualWindowSpecsEqual';
import { areWorkerStatsEqual } from './utils/areWorkerStatsEqual';
import { cleanLastNewline } from './utils/cleanLastNewline';
import { createAnnotationElement } from './utils/createAnnotationElement';
import { createAnnotationWrapperNode } from './utils/createAnnotationWrapperNode';
import { createEmptyRowBuffer } from './utils/createEmptyRowBuffer';
import { createFileHeaderElement } from './utils/createFileHeaderElement';
import type { CreateFileHeaderElementProps } from './utils/createFileHeaderElement';
import { createGutterUtilityContentNode } from './utils/createGutterUtilityContentNode';
import { createGutterUtilityElement } from './utils/createGutterUtilityElement';
import { createNoNewlineElement } from './utils/createNoNewlineElement';
import { createPreElement, createPreWrapperProperties } from './utils/createPreElement';
import { createRowNodes } from './utils/createRowNodes';
import { createSeparator } from './utils/createSeparator';
import { createSpanFromToken } from './utils/createSpanNodeFromToken';
import { createStyleElement, createThemeStyleElement } from './utils/createStyleElement';
import { createTransformerWithState } from './utils/createTransformerWithState';
import { createUnsafeCSSStyleNode } from './utils/createUnsafeCSSStyleNode';
import { createWindowFromScrollPosition } from './utils/createWindowFromScrollPosition';
import { patchScrollbarGutterSize, wrapCoreCSS, wrapThemeCSS, wrapUnsafeCSS } from './utils/cssWrappers';
import { detachString, releaseStringDetachBuffer } from './utils/detachString';
import { diffAcceptRejectHunk } from './utils/diffAcceptRejectHunk';
import { formatCSSVariablePrefix } from './utils/formatCSSVariablePrefix';
import { EXTENSION_TO_FILE_FORMAT, getCustomExtensionsMap, getCustomExtensionsVersion, getFiletypeFromFileName, replaceCustomExtensions, setCustomExtension } from './utils/getFiletypeFromFileName';
import { getHighlighterOptions } from './utils/getHighlighterOptions';
import { getHighlighterThemeStyles } from './utils/getHighlighterThemeStyles';
import { getHunkSeparatorSlotName } from './utils/getHunkSeparatorSlotName';
import { getIconForType } from './utils/getIconForType';
import { getLineAnnotationName } from './utils/getLineAnnotationName';
import { getLineEndingType } from './utils/getLineEndingType';
import { getLineNodes } from './utils/getLineNodes';
import { getOrCreateCodeNode } from './utils/getOrCreateCodeNode';
import { getSingularPatch } from './utils/getSingularPatch';
import { getThemes } from './utils/getThemes';
import { getTotalLineCountFromHunks } from './utils/getTotalLineCountFromHunks';
import { createGutterGap, createGutterItem, createGutterWrapper, createHastElement, createIconElement, createTextNodeElement, findCodeElement } from './utils/hast_utils';
import { isDefaultRenderRange } from './utils/isDefaultRenderRange';
import { isWorkerContext } from './utils/isWorkerContext';
import { createDiffSpanDecoration, pushOrJoinSpan } from './utils/parseDiffDecorations';
import { parseDiffFromFile } from './utils/parseDiffFromFile';
import { parseLineType } from './utils/parseLineType';
import type { ParsedLine } from './utils/parseLineType';
import { parsePatchFiles, processFile, processPatch } from './utils/parsePatchFiles';
import { prefersReducedMotion } from './utils/prefersReducedMotion';
import { prerenderHTMLIfNecessary } from './utils/prerenderHTMLIfNecessary';
import { processLine } from './utils/processLine';
import { renderDiffWithHighlighter } from './utils/renderDiffWithHighlighter';
import { renderFileWithHighlighter } from './utils/renderFileWithHighlighter';
import { resolveConflict } from './utils/resolveConflict';
import { resolveRegion } from './utils/resolveRegion';
import { setLanguageOverride } from './utils/setLanguageOverride';
import { setPreNodeProperties } from './utils/setWrapperNodeProps';
import { trimPatchContext } from './utils/trimPatchContext';
import { codeToHtml, createCssVariablesTheme as createCSSVariablesTheme } from 'shiki';

export { ALTERNATE_FILE_NAMES_GIT, AttachedLanguages, AttachedThemes, COMMIT_METADATA_SPLIT, CORE_CSS_ATTRIBUTE, CUSTOM_HEADER_SLOT_ID, CodeToTokenTransformStream, CodeView, DEFAULT_CODE_VIEW_FILE_METRICS, DEFAULT_CODE_VIEW_LAYOUT, DEFAULT_COLLAPSED_CONTEXT_THRESHOLD, DEFAULT_EXPANDED_REGION, DEFAULT_RENDER_RANGE, DEFAULT_SMOOTH_SCROLL_SETTINGS, DEFAULT_THEMES, DEFAULT_TOKENIZE_MAX_LENGTH, DEFAULT_VIRTUAL_FILE_METRICS, DIFFS_DEVELOPMENT_BUILD, DIFFS_SCROLLBAR_GUTTER_MEASURED_PROPERTY, DIFFS_SCROLLBAR_MEASURE_ATTRIBUTE, DIFFS_TAG_NAME, DiffHunksRenderer, EMPTY_RENDER_RANGE, EXTENSION_TO_FILE_FORMAT, FILENAME_HEADER_REGEX, FILENAME_HEADER_REGEX_GIT, FILE_CONTEXT_BLOB, File, FileDiff, FileRenderer, FileStream, GIT_DIFF_FILE_BREAK_REGEX, HEADER_METADATA_SLOT_ID, HEADER_PREFIX_SLOT_ID, HUNK_HEADER, INDEX_LINE_METADATA, InteractionManager, MERGE_CONFLICT_BASE_MARKER_REGEX, MERGE_CONFLICT_END_MARKER_REGEX, MERGE_CONFLICT_SEPARATOR_MARKER_REGEX, MERGE_CONFLICT_START_MARKER_REGEX, RegisteredCustomLanguages, ResizeManager, ResolvedLanguages, ResolvingLanguages, SPLIT_WITH_NEWLINES, SVGSpriteSheet, ScrollSyncManager, ShikiStreamTokenizer, THEME_CSS_ATTRIBUTE, UNIFIED_DIFF_FILE_BREAK_REGEX, UNSAFE_CSS_ATTRIBUTE, UnresolvedFile, VirtualizedFile, VirtualizedFileDiff, Virtualizer, areDiffLineAnnotationsEqual, areDiffRenderOptionsEqual, areDiffTargetsEqual, areFileRenderOptionsEqual, areFilesEqual, areHunkDataEqual, areLanguagesAttached, areLineAnnotationsEqual, areObjectsEqual, areOptionsEqual, arePrePropertiesEqual, areRenderRangesEqual, areSelectionsEqual, areThemesAttached, areThemesEqual, areVirtualWindowSpecsEqual, areWorkerStatsEqual, attachResolvedLanguages, attachResolvedThemes, cleanLastNewline, cleanUpResolvedLanguages, cleanUpResolvedThemes, codeToHtml, createAnnotationElement, createAnnotationWrapperNode, createCSSVariablesTheme, createDiffSpanDecoration, createEmptyRowBuffer, createFileHeaderElement, createGutterGap, createGutterItem, createGutterUtilityContentNode, createGutterUtilityElement, createGutterWrapper, createHastElement, createIconElement, createNoNewlineElement, createPreElement, createPreWrapperProperties, createRowNodes, createSeparator, createSpanFromToken, createStyleElement, createTextNodeElement, createThemeStyleElement, createTransformerWithState, createUnsafeCSSStyleNode, createWindowFromScrollPosition, dequeueRender, detachString, diffAcceptRejectHunk, disposeHighlighter, findCodeElement, formatCSSVariablePrefix, getCustomExtensionsMap, getCustomExtensionsVersion, getFiletypeFromFileName, getHighlighterIfLoaded, getHighlighterOptions, getHighlighterThemeStyles, getHunkSeparatorSlotName, getIconForType, getLineAnnotationName, getLineEndingType, getLineNodes, getOrCreateCodeNode, getResolvedLanguages, getResolvedOrResolveLanguage, getResolvedOrResolveTheme, getResolvedThemes, getSharedHighlighter, getSingularPatch, getThemes, getTotalLineCountFromHunks, getUnresolvedDiffHunksRendererOptions, hasResolvedLanguages, hasResolvedThemes, isDefaultRenderRange, isHighlighterLoaded, isHighlighterLoading, isHighlighterNull, isWorkerContext, parseDiffFromFile, parseLineType, parsePatchFiles, patchScrollbarGutterSize, pluckInteractionOptions, prefersReducedMotion, preloadHighlighter, prerenderHTMLIfNecessary, processFile, processLine, processPatch, pushOrJoinSpan, queueRender, registerCustomCSSVariableTheme, registerCustomLanguage, registerCustomTheme, releaseStringDetachBuffer, renderDiffWithHighlighter, renderFileWithHighlighter, replaceCustomExtensions, resolveConflict, resolveLanguage, resolveLanguages, resolveRegion, resolveTheme, resolveThemes, setCustomExtension, setLanguageOverride, setPreNodeProperties, trimPatchContext, wrapCoreCSS, wrapThemeCSS, wrapUnsafeCSS };
export type { AnnotationLineMap, AnnotationSide, AnnotationSpan, AppliedThemeStyleCache, BaseCodeOptions, BaseDiffOptions, BaseDiffOptionsWithDefaults, BundledLanguage, ChangeContent, ChangeTypes, CodeColumnType, CodeToHastOptions, CodeToTokenTransformStreamOptions, CodeViewCoordinator, CodeViewDiffItem, CodeViewFileItem, CodeViewItem, CodeViewItemScrollTarget, CodeViewLayout, CodeViewLineScrollTarget, CodeViewLineSelection, CodeViewOptions, CodeViewPositionScrollTarget, CodeViewRangeScrollTarget, CodeViewRenderedDiffItem, CodeViewRenderedFileItem, CodeViewRenderedItem, CodeViewScrollBehavior, CodeViewScrollListener, CodeViewScrollTarget, ConflictResolverTypes, ContextContent, CreateFileHeaderElementProps, CreatePatchOptionsNonabortable, CustomPreProperties, CustomThemeLoader, DecorationItem, DiffAcceptRejectHunkConfig, DiffAcceptRejectHunkType, DiffHunksRendererOptions, DiffHunksRendererOptionsWithDefaults, DiffIndicators, DiffLineAnnotation, DiffLineEventBaseProps, DiffTokenEventBaseProps, DiffsHighlighter, DiffsThemeNames, ExpansionDirections, ExtensionFormatMap, FileContents, FileDiffHydrationProps, FileDiffMetadata, FileDiffOptions, FileDiffRenderProps, FileDiffType, FileHeaderRenderMode, FileHydrateProps, FileOptions, FileRenderProps, FileRenderResult, FileRendererOptions, FileStreamOptions, ForceDiffPlainTextOptions, ForceFilePlainTextOptions, GapSpan, GetHoveredLineResult, GetLineIndexUtility, HighlighterTypes, Hunk, HunkData, HunkExpansionRegion, HunkLineType, HunkSeparators, HunksRenderResult, InjectedRow, InteractionManagerBaseOptions, InteractionManagerMode, InteractionManagerOptions, LanguageRegistration, LineAnnotation, LineDecoration, LineDiffTypes, LineEventBaseProps, LineInfo, LineSpans, LineTypes, LogTypes, MergeConflictActionPayload, MergeConflictActionTarget, MergeConflictActionsTypeOption, MergeConflictMarkerRow, MergeConflictMarkerRowType, MergeConflictRegion, MergeConflictResolution, NumericScrollLineAnchor, ObservedAnnotationNodes, ObservedGridNodes, OnDiffLineClickProps, OnDiffLineEnterLeaveProps, OnLineClickProps, OnLineEnterLeaveProps, OnTokenEventProps, ParsedLine, ParsedPatch, PendingCodeViewLayoutReset, PostRenderPhase, PrePropertiesConfig, ProcessFileConflictData, RecallToken, RenderDiffFilesResult, RenderDiffOptions, RenderDiffResult, RenderFileMetadata, RenderFileOptions, RenderFileResult, RenderHeaderMetadataCallback, RenderHeaderPrefixCallback, RenderMergeConflictActions, RenderRange, RenderWindow, RenderedDiffASTCache, RenderedFileASTCache, RenderedLineContext, SVGSpriteNames, SelectedLineRange, SelectionPoint, SelectionSide, SelectionWriteOptions, SharedRenderState, ShikiStreamTokenizerEnqueueResult, ShikiStreamTokenizerOptions, ShikiTransformer, SmoothScrollSettings, SplitInjectedRow, SplitInjectedRowPlacement, SplitLineDecorationProps, StickySpecs, SupportedLanguages, ThemeRegistration, ThemeRegistrationResolved, ThemeTypes, ThemedDiffResult, ThemedFileResult, ThemedToken, ThemesType, TokenEventBase, UnifiedInjectedRowPlacement, UnifiedLineDecorationProps, UnresolvedFileHydrationProps, UnresolvedFileOptions, UnresolvedFileRenderProps, VirtualFileMetrics, VirtualWindowSpecs, VirtualizerConfig };
